# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Latex
version:      3.00_04
version_from: lib/Template/Plugin/Latex.pm
installdirs:  site
requires:
    LaTeX::Driver:                 0.07
    LaTeX::Encode:                 0.02
    LaTeX::Table:                  0
    Template:                      2.16

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
