---
abstract: 'Latex support for the Template Toolkit'
author:
  - 'Andrew Ford <a.ford@ford-mason.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Latex
no_index:
  directory:
    - t
    - inc
requires:
  LaTeX::Driver: 0.07
  LaTeX::Encode: 0.02
  LaTeX::Table: 0
  Template: 2.16
version: 3.03
